---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: kyverno
  namespace: kyverno-system
spec:
  interval: 75m
  chart:
    spec:
      # renovate: registryUrl=https://helm.releases.hashicorp.com
      chart: kyverno
      version: 3.4.0
      sourceRef:
        kind: HelmRepository
        name: kyverno-charts
        namespace: flux-system