apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: repo
  namespace: flux-system
spec:
  interval: 5m0s
  path: repos
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system