---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: kubescape
  namespace: kubescape
spec:
  interval: 75m
  chart:
    spec:
      # renovate: registryUrl=https://helm.releases.hashicorp.com
      chart: kubescape-operator
      version: 1.27.3
      sourceRef:
        kind: HelmRepository
        name: kubescape-charts
        namespace: flux-system
  values:
    clusterName: "secure-gitops"

    # Account ID (required, use placeholder if not using ARMO SaaS)
    account: "local-kubernetes"

    configurations:
      persistence: disable

    # Enable specific capabilities
    capabilities:
      continuousScan: enable
      configurationScan: enable
      nodeScan: enable

    # Kubescape scheduler configuration for scheduled scans
    kubescapeScheduler:
      scanSchedule: "0 * * * *"

    # Resource limits and requests for Kubescape components
    kubescape:
      resources:
        requests:
          cpu: "500m"
          memory: "500Mi"
        limits:
          cpu: "1000m"
          memory: "1000Mi"

    kubevuln:
      resources:
        requests:
          cpu: "500m"
          memory: "500Mi"
        limits:
          cpu: "1000m"
          memory: "1000Mi"

    operator:
      resources:
        requests:
          cpu: "500m"
          memory: "500Mi"
        limits:
          cpu: "1000m"
          memory: "1000Mi"

    storage:
      resources:
        requests:
          cpu: "500m"
          memory: "500Mi"
        limits:
          cpu: "1000m"
          memory: "1000Mi"
    

    # Namespace for Kubescape Operator
    namespace: kubescape