
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-kyverno-policies
  namespace: flux-system
spec:
  interval: 1h
  path: cluster/apps/kyverno-system/policies/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system

